name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: write
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: bufbuild/buf-action@v1
    #   - run: buf generate --error-format github-actions
    #   - uses: stefanzweifel/git-auto-commit-action@v5
    #     with:
    #       commit_message: Generate code from protos
    #       commit_author: ${{ steps.last-commit.outputs.author }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Buf action
      - uses: bufbuild/buf-action@v1

      - name: Generate proto code
      - run: buf generate --error-format github-actions
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate code from protos
          commit_author: ${{ steps.last-commit.outputs.author }}

