name: Buf CI
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  contents: write
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Buf action
        uses: bufbuild/buf-action@v1

      - name: Generate proto code
        run: buf generate --error-format github-actions

      - name: Commit code change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate code from protos
          commit_author: ${{ steps.last-commit.outputs.author }}

